### ISSUE TITLE
Generate table of contents in readmes

### ISSUE THREAD

**Issue by damemi** [GoogleCloudPlatform/opentelemetry-operator-sample#18]
Similar to https://github.com/GoogleCloudPlatform/opentelemetry-collector-builder-sample/issues/18, we should generate the table of contents for the main readme and subdirectory readmes in the sample-apps and recipes folders. This generation should be verified in a presubmit for new PRs

**Comment by aabmass** [comment]
Not a high priority but would be nice to have. Github generates a TOC if you click the hamburger icon on an MD file, but it's not the greatest.

**Comment by damemi** [comment]
Github automatically generates a dropdown readme list now, so this is obsolete
