### ISSUE TITLE
Define thorough operator integration test plan

### ISSUE THREAD

**Issue by damemi** [GoogleCloudPlatform/opentelemetry-operator-sample#23]
Come up with a test/CI plan for making sure our recipes work on GKE (and with other GCP components)

**Comment by aabmass** [comment]
Mike is working on it

**Comment by damemi** [comment]
At this point we have an idea of the test plan we want and I've shared a doc outlining the rough design for that. However a thorough plan is not a high priority for us right now. If this comes back up we will open a new issue to track implementing the tests.
