### ISSUE TITLE
Can't start collector - failed to call webhook - context deadline exceeded

### ISSUE THREAD

**Issue by gbajson-area22** [GoogleCloudPlatform/opentelemetry-operator-sample#29]
This is a problem in GKE Autopilot cluster version `1.25.6-gke.1000`.

I follow the guide from https://github.com/GoogleCloudPlatform/opentelemetry-operator-sample#prerequisites.

I installed `cert-manager` and OpenTelemetry Operator. 
I can't start collector, here is the error:

```bash
$ kubectl apply -f collector-config.yaml 
Error from server (InternalError): error when creating "collector-config.yaml": Internal error occurred: failed calling webhook "mopentelemetrycollector.kb.io": failed to call webhook: Post "https://opentelemetry-operator-webhook-service.opentelemetry-operator-system.svc:443/mutate-opentelemetry-io-v1alpha1-opentelemetrycollector?timeout=10s": context deadline exceeded
```

**Comment by damemi** [comment]
Hi @gbajson-area22, just a guess, but it sounds like maybe the operator pod isn't yet running/ready to serve the webhooks that process the Collector object. Is this by any chance a fresh autopilot cluster? If so, new clusters can take some time to scale up for all pods to be scheduled (including the operator pod).

**Comment by gbajson-area22** [comment]
Thanks for your response.
This is not fresh cluster and "opentelemetry-operator-controller-manager"
Pod successfully started.There are no errors in Pod's logs.
According to logs, `v1alpha1.OpenTelemetryCollector"` tried to start.

```
{"level":"info","ts":"2023-03-22T15:15:08.833041327Z","msg":"Starting
EventSource","controller":"opentelemetrycollector","controllerGroup":"
opentelemetry.io","controllerKind":"OpenTelemetryCollector","source":"kind
source: *v1alpha1.OpenTelemetryCollector"}
{"level":"info","ts":"2023-03-22T15:15:08.833121793Z","msg":"Starting
EventSource","controller":"opentelemetrycollector","controllerGroup":"
opentelemetry.io","controllerKind":"OpenTelemetryCollector","source":"kind
source: *v1.ConfigMap"}
{"level":"info","ts":"2023-03-22T15:15:08.833165633Z","msg":"Starting
EventSource","controller":"opentelemetrycollector","controllerGroup":"
opentelemetry.io","controllerKind":"OpenTelemetryCollector","source":"kind
source: *v1.ServiceAccount"}
{"level":"info","ts":"2023-03-22T15:15:08.833180179Z","msg":"Starting
EventSource","controller":"opentelemetrycollector","controllerGroup":"
opentelemetry.io","controllerKind":"OpenTelemetryCollector","source":"kind
source: *v1.Service"}
{"level":"info","ts":"2023-03-22T15:15:08.833188249Z","msg":"Starting
EventSource","controller":"opentelemetrycollector","controllerGroup":"
opentelemetry.io","controllerKind":"OpenTelemetryCollector","source":"kind
source: *v1.Deployment"}
{"level":"info","ts":"2023-03-22T15:15:08.833195283Z","msg":"Starting
EventSource","controller":"opentelemetrycollector","controllerGroup":"
opentelemetry.io","controllerKind":"OpenTelemetryCollector","source":"kind
source: *v1.DaemonSet"}
{"level":"info","ts":"2023-03-22T15:15:08.833201818Z","msg":"Starting
EventSource","controller":"opentelemetrycollector","controllerGroup":"
opentelemetry.io","controllerKind":"OpenTelemetryCollector","source":"kind
source: *v1.StatefulSet"}
{"level":"info","ts":"2023-03-22T15:15:08.833209363Z","msg":"Starting
EventSource","controller":"opentelemetrycollector","controllerGroup":"
opentelemetry.io","controllerKind":"OpenTelemetryCollector","source":"kind
source: *v2.HorizontalPodAutoscaler"}
{"level":"info","ts":"2023-03-22T15:15:08.833214042Z","msg":"Starting
Controller","controller":"opentelemetrycollector","controllerGroup":"
opentelemetry.io","controllerKind":"OpenTelemetryCollector"}
{"level":"info","ts":"2023-03-22T15:15:08.993565055Z","logger":"instrumentation-upgrade","msg":"no
instances to upgrade"}
{"level":"info","ts":"2023-03-22T15:15:08.993882768Z","logger":"collector-upgrade","msg":"no
instances to upgrade"}
{"level":"info","ts":"2023-03-22T15:15:09.195660699Z","msg":"Starting
workers","controller":"opentelemetrycollector","controllerGroup":"
opentelemetry.io","controllerKind":"OpenTelemetryCollector","worker
count":1}
```

**Comment by damemi** [comment]
@gbajson-area22 thanks for clarifying. It does look like the operator pod starts up fine and is watching for objects to be created.

I found a couple other issues scattered around that are similar to this: https://github.com/open-telemetry/opentelemetry-operator/issues/100 https://github.com/open-telemetry/opentelemetry-operator/issues/1009. I tried reproducing this on a couple new GKE autopilot clusters and wasn't able to unfortunately.

Could you confirm that you installed cert-manager using the special helm instructions in https://github.com/GoogleCloudPlatform/opentelemetry-operator-sample#prerequisites?

Also, is this a private GKE cluster? You may need to make a firewall rule for the webhook port based on this comment: https://github.com/open-telemetry/opentelemetry-operator/issues/100#issuecomment-846125541

**Comment by gbajson-area22** [comment]
Hi Mike,
1. Yes, I installed cert-manager using instructions from
https://github.com/GoogleCloudPlatform/opentelemetry-operator-sample#prerequisites
2. Yes, this is a private GKE cluster. Thanks for this link, I will test it.

**Comment by damemi** [comment]
Thanks for the quick reply. Please let me know if that helps and if so I'll update our docs to include it

**Comment by damemi** [comment]
I was able to reproduce this in a private cluster and the fix linked above worked for me. Opened https://github.com/GoogleCloudPlatform/opentelemetry-operator-sample/pull/32 to document this and that will close this issue.

**Comment by gbajson-area22** [comment]
Thank you!
