### ISSUE TITLE
Sample for Operator auto-instrumentation with Go

### ISSUE THREAD

**Issue by wagnerww** [GoogleCloudPlatform/opentelemetry-operator-sample#30]
Do you have any predictions for auto instrumentation with GO using GKE/ASM?

**Comment by damemi** [comment]
Support in the operator for go auto-instrumentation is in progress at https://github.com/open-telemetry/opentelemetry-operator/pull/1555. This is pretty much just waiting on the first tagged alpha release of https://github.com/open-telemetry/opentelemetry-go-instrumentation, which should be soon.

Once the operator supports it, we'll add an example for it here. There is also a compile-time auto instrumentation for Go available at https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/instrgen, which is usable now but won't be available in the operator at least for the time being.

I'll leave this issue open to track adding support once it's available

**Comment by damemi** [comment]
I opened a PR to add a go sample app in https://github.com/GoogleCloudPlatform/opentelemetry-operator-sample/pull/35, the client doesn't work with the current latest go auto-instrumentation but it should be fixed in the next release. We can merge it then
