### ISSUE TITLE
Error on exporting Metrics to Google Cloud

### ISSUE THREAD

**Issue by radioactive11** [GoogleCloudPlatform/opentelemetry-operator-sample#34]
There seems to be a problem with the metric exporter. On following the guide for exporting metrics to Google Cloud, I was facing the following error.

### Collector version

0.75.0

## Environment
GKE

### OpenTelemetry Collector configuration

```yaml
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel
spec:
  image: otel/opentelemetry-collector-contrib:latest
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
    exporters:
      googlecloud:
        metric:
          create_service_timeseries: true
          use_insecure: true
          prefix: "eevee"
      logging:
        loglevel: debug
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [googlecloud]
        metrics:
          receivers: [otlp]
          processors: []
          exporters: [googlecloud]
```

### Log output

```shell
│ 2023-04-17T09:42:48.503Z    info    service/telemetry.go:90    Setting up own telemetry...                                                                                                                                                                                   │
│ 2023-04-17T09:42:48.503Z    info    service/telemetry.go:116    Serving Prometheus metrics    {"address": ":8888", "level": "Basic"}                                                                                                                                         │
│ Error: failed to build pipelines: failed to create "googlecloud" exporter for data type "metrics": no project set in config, or found with application default credentials                                                                                                   │
│ 2023/04/17 09:42:48 collector server run finished with error: failed to build pipelines: failed to create "googlecloud" exporter for data type "metrics": no project set in config, or found with application default credentials
```

Also, please consider adding recipes for exporting metrics to Google Cloud.

Thank You!

**Comment by radioactive11** [comment]
Hello @damemi 
Yes I am running this operator on GKE

**Comment by damemi** [comment]
Thanks, in that case it should be picking up the project ID from the GKE metadata by default. Does this cluster use workload identity?

As a workaround, you could try setting `googlecloud.project` on the exporter like so:

```
exporters:
  googlecloud:
    project: my-project
```

**Comment by radioactive11** [comment]
I have applied the change. The error is not coming up but the metrics are still now showing up on the GCP Metric Explorer.
Just to be sure, the metrics would have the name `workload.googleapis.com` right?

**Comment by damemi** [comment]
That's the domain they'll be under, but you can search for the name itself (eg, if the full metric is `workload.googleapis.com/foo` you can just search `foo`)

Are you using one of the sample apps in this repo or a different one?

**Comment by radioactive11** [comment]
No I am using this on my own project, not the sample app

**Comment by damemi** [comment]
@radioactive11 oh, I was wondering if this was an issue with one of our samples. If the metrics were being rejected, there should be errors in the Collector logs. Can you share those?

One question I still had was if this was a workload identity cluster. There could be some gcp settings you need there, but those would likely show up in the collector logs.

**Comment by damemi** [comment]
I'm going to close this as I think the original issue was addressed.

@radioactive11 if you are still having trouble getting your metrics to show up, please feel free to open a new issue and we can try to diagnose that problem separately. Thanks
