### ISSUE TITLE
Add diagrams

### ISSUE THREAD

**Issue by damemi** [GoogleCloudPlatform/opentelemetry-operator-sample#6]
For the samples, recipes, and even basic install, it would be nice to have diagrams so users can visualize the end state of each one.

**Comment by aabmass** [comment]
This is not a high priority but would be nice to have

**Comment by damemi** [comment]
This has been open for a while with no traction, I think we are pretty good on diagrams. They would have been "nice to have" but I don't see us allocating effort any time soon to put them together. We can reopen this if we do
