### ISSUE TITLE
Expand beyla recipe to include a service graph

### ISSUE THREAD

**Issue by dashpole** [GoogleCloudPlatform/opentelemetry-operator-sample#62]
The traces we get from beyla aren't really that useful, as they aren't properly integrated into the trace tree.  We should use them to produce a service graph instead of sending them to cloud trace.  This should be feasible using the [servicegraphconnector](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/connector/servicegraphconnector/README.md).

**Comment by aabmass** [comment]
Was fixed by #65
